### ISSUE TITLE
create social links

### ISSUE THREAD

**Issue by seanwooj** [seanwooj/quotenote#14]
@jeremyquotenote - can you give me tha links?

**Comment by jeremyquotenote** [comment]
https://instagram.com/quotenote_it/
https://twitter.com/QUOTENOTE_it
http://quotenote-it.tumblr.com/  (this needs an updated cover photo)
https://www.facebook.com/pages/QuoteNote/575718842568593

We have a Pinterest link but I haven't been posting.

https://www.pinterest.com/quotenote/

**Comment by seanwooj** [comment]
rudimentary, but enough for now.
