### ISSUE TITLE
OrdersController#create (ActionView::Template::Error) "undefined method `has_errors?' for #<OrderForm:0xXXXXXX>"

### ISSUE THREAD

**Issue by quotenote** [seanwooj/quotenote#30]
<table><tr><th>Exception</th><td>undefined method `has_errors?&#39; for #&lt;OrderForm:0x007f90be443eb8&gt;</td></tr><tr><th>Last Occurrence</th><td>May 11, 2015 19:24:22 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/seanwooj/quotenote/blob/21debce557f4771b61ded6f89acf731c681021ca/app/views/orders/_errors.html.haml#L1'>[app].../app/views/orders/_errors.html.haml:1:in `_app_views_orders__errors_html_haml__385894308696479998_70129859200500'</a>
[bundle].../gems/actionview-4.2.0/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
[bundle].../gems/actionview-4.2.0/lib/action_view/template.rb:333:in `instrument'
[bundle].../gems/actionview-4.2.0/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/partial_renderer.rb:309:in `render'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/renderer.rb:47:in `render_partial'
[bundle].../gems/actionview-4.2.0/lib/action_view/helpers/rendering_helper.rb:35:in `render'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
[bundle].../gems/haml-4.0.6/lib/haml/helpers.rb:89:in `non_haml'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
<a href='https://github.com/seanwooj/quotenote/blob/21debce557f4771b61ded6f89acf731c681021ca/app/views/carts/checkout.html.haml#L10'>[app].../app/views/carts/checkout.html.haml:10:in `block in _app_views_carts_checkout_html_haml__3440890366848310219_70129792585360'</a>
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:137:in `call'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:137:in `block (2 levels) in form_for_with_haml'
[bundle].../gems/haml-4.0.6/lib/haml/helpers.rb:278:in `with_tabs'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:137:in `block in form_for_with_haml'
[bundle].../gems/actionview-4.2.0/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
[bundle].../gems/actionview-4.2.0/lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
[bundle].../gems/actionview-4.2.0/lib/action_view/helpers/capture_helper.rb:38:in `capture'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
[bundle].../gems/actionview-4.2.0/lib/action_view/helpers/form_helper.rb:444:in `form_for'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
<a href='https://github.com/seanwooj/quotenote/blob/21debce557f4771b61ded6f89acf731c681021ca/app/views/carts/checkout.html.haml#L9'>[app].../app/views/carts/checkout.html.haml:9:in `_app_views_carts_checkout_html_haml__3440890366848310219_70129792585360'</a>
[bundle].../gems/actionview-4.2.0/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
[bundle].../gems/actionview-4.2.0/lib/action_view/template.rb:333:in `instrument'
[bundle].../gems/actionview-4.2.0/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/template_renderer.rb:14:in `render'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/renderer.rb:42:in `render_template'
[bundle].../gems/actionview-4.2.0/lib/action_view/renderer/renderer.rb:23:in `render'
[bundle].../gems/actionview-4.2.0/lib/action_view/rendering.rb:100:in `_render_template'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/streaming.rb:217:in `_render_template'
[bundle].../gems/actionview-4.2.0/lib/action_view/rendering.rb:83:in `render_to_body'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
[bundle].../gems/actionpack-4.2.0/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/seankim/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
[bundle].../gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:40:in `render'
<a href='https://github.com/seanwooj/quotenote/blob/21debce557f4771b61ded6f89acf731c681021ca/app/controllers/orders_controller.rb#L41'>[app].../app/controllers/orders_controller.rb:41:in `rescue in create'</a>
<a href='https://github.com/seanwooj/quotenote/blob/21debce557f4771b61ded6f89acf731c681021ca/app/controllers/orders_controller.rb#L37'>[app].../app/controllers/orders_controller.rb:37:in `create'</a>
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal.rb:195:in `dispatch'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.0/lib/action_controller/metal.rb:236:in `block in action'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:42:in `serve'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/pdfkit-0.6.2/lib/pdfkit/middleware.rb:17:in `call'
[bundle].../gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
[bundle].../gems/rack-1.6.1/lib/rack/etag.rb:24:in `call'
[bundle].../gems/rack-1.6.1/lib/rack/conditionalget.rb:38:in `call'
[bundle].../gems/rack-1.6.1/lib/rack/head.rb:13:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/rack-1.6.1/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.1/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
[bundle].../gems/activerecord-4.2.0/lib/active_record/migration.rb:378:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
[bundle].../gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:73:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/web-console-2.1.2/lib/web_console/middleware.rb:37:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.6.1/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/rack-1.6.1/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/rack-1.6.1/lib/rack/lock.rb:17:in `call'
[bundle].../gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
[bundle].../gems/rack-1.6.1/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
[bundle].../gems/rack-1.6.1/lib/rack/content_length.rb:15:in `call'
[bundle].../gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
[bundle].../gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
[bundle].../gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
[bundle].../gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
[bundle].../gems/unicorn-rails-2.2.0/lib/unicorn_rails.rb:33:in `run'
[bundle].../gems/rack-1.6.1/lib/rack/server.rb:286:in `start'
[bundle].../gems/railties-4.2.0/lib/rails/commands/server.rb:80:in `start'
[bundle].../gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
[bundle].../gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
[bundle].../gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
[bundle].../gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
[bundle].../gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
<a href='https://github.com/seanwooj/quotenote/blob/21debce557f4771b61ded6f89acf731c681021ca/bin/rails#L8'>[app].../bin/rails:8:in `require'</a>
<a href='https://github.com/seanwooj/quotenote/blob/21debce557f4771b61ded6f89acf731c681021ca/bin/rails#L8'>[app].../bin/rails:8:in `<top (required)>'</a>
[bundle].../gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `load'
[bundle].../gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `call'
[bundle].../gems/spring-1.3.6/lib/spring/client/command.rb:7:in `call'
[bundle].../gems/spring-1.3.6/lib/spring/client.rb:26:in `run'
[bundle].../gems/spring-1.3.6/bin/spring:48:in `<top (required)>'
[bundle].../gems/spring-1.3.6/lib/spring/binstub.rb:11:in `load'
[bundle].../gems/spring-1.3.6/lib/spring/binstub.rb:11:in `<top (required)>'
<a href='https://github.com/seanwooj/quotenote/blob/21debce557f4771b61ded6f89acf731c681021ca/bin/spring#L13'>[app].../bin/spring:13:in `require'</a>
<a href='https://github.com/seanwooj/quotenote/blob/21debce557f4771b61ded6f89acf731c681021ca/bin/spring#L13'>[app].../bin/spring:13:in `<top (required)>'</a>
bin/rails:3:in `load'
bin/rails:3:in `<main>'</pre>
Fingerprint: `d37d2c46d752b5a69f8d7217101e276b6a345cbd`

**Comment by seanwooj** [comment]
fixed
